# Generated by Django 3.0.4 on 2020-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Created At")),
                (
                    "modiefied_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified At"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Budget"
                    ),
                ),
                (
                    "incomes",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Incomes"
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Expenses"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "modiefied_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified At"),
                ),
                ("concept", models.CharField(max_length=50, verbose_name="Concept")),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Clothe", "Clothe"),
                            ("Food", "Food"),
                            ("Rent", "Rent"),
                            ("Technology", "Technology"),
                            ("Travel", "Travel"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "modiefied_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified At"),
                ),
                ("concept", models.CharField(max_length=50, verbose_name="Concept")),
                ("value", models.CharField(max_length=50, verbose_name="Value")),
                (
                    "category",
                    models.CharField(
                        choices=[("Work", "Work"), ("Freelance", "Freelance")],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
