# Generated by Django 3.0.4 on 2020-03-17 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(verbose_name='Since')),
                ('until', models.DateTimeField(verbose_name='Until')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('year', models.CharField(max_length=10, verbose_name='Year')),
                ('incomes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('expenses', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name_plural': 'Budget'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Food', 'Food'), ('Rent', 'Rent'), ('Technology', 'Technology'), ('Travel', 'Travel')], max_length=50, verbose_name='Category'),
        ),
    ]
